
server.port: 8080
server.ssl.enabled: false
server.ssl.key-store: classpath:keystore.jks
server.ssl.key-store-password: changeit


nofdev:
  connection:
    defaultConnectionTimeout: 5000
    defaultSoTimeout: 10000
    maxPerRoute: 100
    maxTotalConnection: 1000
    defaultConnectionRequestTimeout: 1000
  proxy:
    url:
      userService: http://localhost:9999

---
spring:
  profiles: development
  
---
spring:
  profiles: testing
  logging.logstash.destination: changeme

---
spring:
  profiles: production
  logging.logstash.destination: changeme
